services:
  server:
    image: ghcr.io/librespeed/speedtest:latest
    container_name: speedtest
    restart: always
    ports:
      - 4000:8080
    environment:
      MODE: standalone
      TELEMETRY: "false"
      WEBPORT: 8080