services:
  server:
    image: wantguns/bin
    container_name: pastebin
    restart: always
    ports:
      - 7000:6163
    environment:
      - BIN_PORT=6163
      - BIN_LIMITS={form="16 MiB"}
      - BIN_CLIENT_DESC=placeholder
    volumes:
      - /home/eren/pastebin:/upload
    networks:
      - home_network
networks:
  home_network:
    external: true