services:
  server:
    image: ghcr.io/xeome/slimserve:latest
    restart: always
    ports:
      - 8000:8080
    volumes:
      - /home/eren/slimserve:/data
    networks:
      - home_network
networks:
  home_network:
    external: true