services:
  server:
    image: ghcr.io/c4illin/convertx:latest
    container_name: convertx
    restart: always
    ports:
      - 2000:3000
    environment:
      - HTTP_ALLOWED=true
      - AUTO_DELETE_EVERY_N_HOURS=48
    volumes:
      - ./data:/app/data
    networks:
      - home_network
networks:
  home_network:
    external: true